### ISSUE TITLE
incompatible with neo4j 1.0

### ISSUE THREAD

**Issue by akollegger** [ept/neo4j-scala-template#1]
The template is out of sync with neo4j-resources, which now seems to use the neo4j 1.0 api.

**Comment by akollegger** [comment]
gist with patch here: http://gist.github.com/360258

**Comment by akollegger** [comment]
Though, that just gets things compiling. The example doesn't work, yet. GET returns a nice message suggesting that I POST to the resource, so that's good. But, POSTs timeout.

**Comment by ept** [comment]
Sorry to take so long on this issue. I have updated the project to work with neo4j 1.0. The example curl requests mentioned in the README work for me. If they are still broken for you, please create a new issue.
